import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import ScrollProvider from "@/providers/scroll-provider";
import Navigation from "@/components/elements/navigation";

const manrope = Manrope({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={manrope.className}
      >
        <ScrollProvider>
          <Navigation />
          {children}
        </ScrollProvider>
      </body>
    </html>
  );
}
